import Head from 'next/head'
import { useState, useEffect } from 'react'
import axios from 'redaxios'
import styles from '@/styles/Home.module.scss'
import LoageCostumize from '@/components/Login/LoadeCostumize/LoadeCostumize'
import Accordion from '@/components/Dashboard/Accordion/Accordion'

const http = axios.create({
  baseURL: 'http://api.poly.com.br',
})

export default function Dashboard() {
  const [tasks, updateTasks] = useState([])
  const [task, updateTask] = useState('')
  const [url, updateUrl] = useState('')
  const [isLoading, updateIsLoading] = useState(false)

  useEffect(() => {
    updateIsLoading(true)
    http.get('/api/tasks').then((response) => {
      updateTasks(response.data.tasks)
      console.log(tasks)
      console.log(response.data)
      updateIsLoading(false)
    })
  }, [])

  const handleAddTask = (event) => {
    event.preventDefault()
    if (task.trim()) {
      updateIsLoading(true)
      http.post('/api/tasks', { url, task }).then((response) => {
        updateTasks((oldTasks) => [
          ...oldTasks,
          { task: response.data.task, url: response.data.url },
        ])
        updateTask('')
        updateUrl('')
        updateIsLoading(false)
      })
    }
  }
  if (isLoading) return <LoageCostumize />
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main_post}>
        <div>
          <h1>posts</h1>
          <form onSubmit={handleAddTask}>
            <input
              onChange={(event) => updateTask(event.target.value)}
              value={task}
              placeholder="Descricao"
            />
            <input
              onChange={(event) => updateUrl(event.target.value)}
              value={url}
              placeholder="url"
            />
            <button>Add</button>
          </form>
        </div>
        <Accordion tasks={tasks} id={tasks.id} />
      </main>
    </>
  )
}
