import Head from 'next/head'
import { useState, useEffect } from 'react'
import axios from 'redaxios'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const http = axios.create({
  baseURL: 'http://api.poly.com.br',
})

export default function Dashboard() {
  const [tasks, updateTasks] = useState([])
  const [task, updateTask] = useState('')
  const [isLoading, updateIsLoading] = useState(false)

  useEffect(() => {
    updateIsLoading(true)
    http.get('/api/tasks').then((response) => {
      updateTasks(response.data.tasks)
      updateIsLoading(false)
    })
  }, [])

  const handleAddTask = (event) => {
    event.preventDefault()
    if (task.trim()) {
      updateIsLoading(true)
      http.post('/api/tasks', { task }).then((response) => {
        updateTasks((oldTasks) => [...oldTasks, response.data.task])
        updateTask('')
        updateIsLoading(false)
      })
    }
  }
  if (isLoading) return <h1>Está carregando...</h1>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>posts</h1>
          <form onSubmit={handleAddTask}>
            <input
              onChange={(event) => updateTask(event.target.value)}
              value={task}
            />
            <button>Add</button>
          </form>
          <ul>
            {tasks.map((t) => (
              <li key={t.id}>{t.name}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}
