import Head from 'next/head'
import { useState } from 'react'
import axios from 'redaxios'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })
const http = axios.create({
  baseURL: 'http://api.poly.com.br',
})
export default function Home() {
  const router = useRouter() // Movido o useRouter para fora do escopo da função handleLogin
  const [username, setUsername] = useState('') // Adicionado estado para o nome de usuário
  const [password, setPassword] = useState('')
  const handleLogin = (event) => {
    event.preventDefault()
    http.post('api/login', { username, password }).then((response) => {
      console.log(response)
      router.push('/dashboard')
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form onSubmit={handleLogin}>
          <input onChange={(e) => setUsername(e.target.value)} />
          <input onChange={(e) => setPassword(e.target.value)} />
          <button type="submit">login</button>
        </form>
      </main>
    </>
  )
}
